
LoginCredentials:
  User: null
  Password: null

SessionCredentials:
  SessionID: null
  UserId: null
  CustomerId: null

Daemon:
  Jobs:
    - Name: "Check Account Balance"
      Schedule: "* * * * *"