
LoginCredentials:
  User: null
  Password: null

SessionCredentials:
  SessionID: null
  UserId: null
  CustomerId: null

Daemon:
  Jobs:
    - Name: "Check Account Balance"
      Type: CheckBalance
      Schedule: "* * * * * *"
      Params:
        email: my@mail.de
        minBalance: 5
    - Name: "Order Food"
      Type: Order
      Schedule: "*/45 * * * * *"
