Client:
  LoginCredentials:
    User: null
    Password: null

  SessionCredentials:
    SessionID: null
    UserId: null
    CustomerId: null

Core:
  Daemon:
    Jobs:
      - name: Check Account Balance
        params:
          topic: thinkjd_munch_o_matic
          minbalance: 3000
          template: |
            Your account balance is low: {{.AccountBalance}}€
        schedule: "*/10 * * * * *"
        type: CheckBalance
      - name: Order Food
        params:
          strategy: SchooFav
          weeks: 2
          topic: thinkjd_munch_o_matic
          template: |
            Food order
        schedule: "*/20 * * * * *"
        type: Order
