Client:
  LoginCredentials:
    User: null
    Password: null

  SessionCredentials:
    SessionID: null
    UserId: null
    CustomerId: null

Core:
  Daemon:
    Jobs:
      - name: Check Account Balance
        params:
          topic: my_ntfy_topic
          minbalance: 3000
          template: "Your account balanc is low: {{.User.Customer.AccountBalance.Amount}}ct"
        schedule: "*/10 * * * * *"
        type: CheckBalance
      - name: Update Metrics
        schedule: "0 * * * * *"
        type: UpdateMetrics
      - name: Order Food
        params:
          strategy: SchooFav
          weeks: 2
          topic: my_ntfy_topic
          template: |
            Food order
        schedule: "*/20 * * * * *"
        type: Order
